### ISSUE TITLE
no samples folder

### ISSUE THREAD

**Issue by jonisapp** [felixroos/jazzband#22]
Hello, there is no sample folder in the module. Should it be downloaded elsewhere ?

**Comment by felixroos** [comment]
Yeah they are gitignored because it's rather large and I did not know if it's ok to upload it to github.. I could send them to you if you want

**Comment by felixroos** [comment]
Hm I just checked and it's just a few MB of samples so I added it..

**Comment by felixroos** [comment]
I did not create a new release though as I am not actively maintaining this repo. But you can play around with the code by cloning it and running `npm i && npm run demo` if you want. May I ask why you're interested in this lib, and what you want to do with it?

**Comment by felixroos** [comment]
I stopped working on this lib, as I moved to developing [strudel](https://github.com/tidalcycles/strudel), which is similar (but much more powerful)
