### ISSUE TITLE
Multiple chords in a measure

### ISSUE THREAD

**Issue by lastant** [felixroos/jazzband#7]
I think this is a bug, but it might be a feature ;)
Say I put `| D7 G-7|` into the textarea on the demo page. Then I expect the value of `measures` at
https://github.com/felixroos/jazzband/blob/b2906227d09286f378073d3adac2e4c63715be0c/src/musicians/Bassist.ts#L32 to be like
```
[
  {chord: 'D7', ...
  {chord: 'D7', ...
  {chord: 'G-7', ...
  {chord: 'G-7', ...
]
```
Instead, it is
```
[
  {chord: 'D7', ...
  {chord: 'G-7', ...
  {chord: 'G-7', ...
  {chord: 'G-7', ...
]
```

**Comment by felixroos** [comment]
Yeah this seems to be a bug, also if you listen to the bass (swing), it plays a D on beat 2, but as [this bassist should always play the 5th on beat 2](https://github.com/felixroos/jazzband/blob/master/src/musicians/Bassist.ts#L58) (stupid bassist), this should be an A, while D is already the fifth of the G chord. But it appears to only affect the bass... I guess it must be happening somewhere between [resolveChords](https://github.com/felixroos/jazzband/blob/master/src/util/util.ts#L83) and [getPath](https://github.com/felixroos/jazzband/blob/master/src/util/util.ts#L72) which is a recursive nightmare to debug.
Because I already [reimplemented the rhythmical aspect](https://github.com/felixroos/rhythmical/), I am currently not in the mood to debug this premature code of mine, so either you 
- accept its quirks
- or you try to fix it yourself (PR welcome)
- or you use the newer rhythmical lib along with Tone.js and write your own grooves
- or you wait until I finished my reimplementation of grooves with rhythmical, which will flow back to this project as soon as it's done
- or you use something else

**Comment by lastant** [comment]
I was thinking of fixing it, but then I imagined the case of three chords in a measure like `|A B C|` and thought it should probably convert to `|A B C x|`, and in this case it's logical that `|A B|` converts to `|A x B x|` (which seems to be the case). So writing explicitly `|A x B x|` works for me, I just need to make sure ireal sheets work fine. 

I need that chord info to set the current chord, similar to the onMeasure callback, but for each beat. Btw, what is the best way to get all tones that can be used during a specific chord (for the improvisation purposes)?

**Comment by felixroos** [comment]
briefly looking at [Band.comp](https://github.com/felixroos/jazzband/blob/master/src/Band.ts#L51) there is only the onMeasure callback. Voicings are generated [here](https://github.com/felixroos/jazzband/blob/master/src/musicians/Pianist.ts#L91). 

If you plan to implement new stuff anyway, I strongly recommend you use this stack instead, which is essentially jazzband but each logical part seperated, and further developed: 

- [leetsheet](https://github.com/felixroos/leetsheet/) parses leadsheets (supports ireal format)
- [harmonical](https://github.com/felixroos/harmonical) generates voicings from chord symbols
- [rhythmical](https://github.com/felixroos/rhythmical) if you want to use nested array format for grooves

you would also need

- [Tone.js](https://tonejs.github.io/) for playback (look at Tone.Part)
- [tonal](https://github.com/tonaljs/tonal) for general music theory methods (used by harmonical)

Sorry for just throwing links at you, but I cannot implement this for you... If you have any more specific questions while using the modules above, let me know

**Comment by lastant** [comment]
Thanks for your support, even just links :)
But these voicings are only the chord tones, while I'd like to get all tones that wouldn't sound dissonant with a chord. For instance while the chord C7 is active, playing a D is fine, while a B is not. I couldn't find such a function in Tonaljs either.. Does the Improvisor class only play chord tones?

**Comment by felixroos** [comment]
Picking scales for chords is really tricky if you want to do it right.. The Improviser (which you should see as an experiment) [uses](https://github.com/felixroos/jazzband/blob/master/src/improvisation/methods.ts#L134) [getPatternInChord](https://github.com/felixroos/jazzband/blob/master/src/util/util.ts#L348), which calls [pickChordScale](https://github.com/felixroos/jazzband/blob/master/src/util/util.ts#L258) if the desired pattern contains more than chord notes. [getChordScales](https://github.com/felixroos/jazzband/blob/master/src/util/util.ts#L249) will use [PcSet.isSupersetOf](https://github.com/tonaljs/tonal/tree/master/packages/pcset#issupersetofsubset-set--parent-set--boolean) to determine which (by default Diatonic) scales contain the chord. You can hear how that sounds [here](https://felixroos.github.io/color-tunes/) (select improviser method next to style). 

The problem with this method is, that it won't always work to just pick any diatonic scale that fits the current chord. To really know which notes sound best, some kind of key detection would be needed.

For example, take this progession:

|  C^7  |  F^7  |  B-7b5  |  E-7  |
|  A-7  |  D-7  |  G7     |  C^7  |

which diatonic scales could you play over E-7? theoretically:

- E aeolian (6th degree of G major)
- E dorian (2nd degree of D major)
- E phrygian (3rd degree of C major)

For the progression, only E phrygian makes sense as the surrounding chords are clearly part of C major. Both aeolian and dorian will have a natural 9 (F#) which is not part of C major. E dorian has a major sixth (C#), which is also not part of C major. Playing these "wrong" notes will sound outside which you may want sometimes, but not all the time..

**Comment by lastant** [comment]
I am also trying to use the RealParser, but it doesn't seem to work with strings I'm testing like:
`irealb://Ali%C3%A1s%3DDjavan%3D%3DBallad%3DC%3D%3D1r34LbKcu7%2C6-bB4C%5E7XDZL7A%207bB%7CQyX7E-ZL9b7B%207h%23F%7CQy-%5E7%20s4TA*%5B7F%2096D-7%20G%20QyXQyX%5D%207G%207-ZDL7obE%207-E1NZL9LZN2Cl%7C%2C7ALZC%5E7XyQZ%20%3DLatin-Brazil:%20Bossa%20Acoustic%3D70%3D3%3D%3D%3D` 
Do I need to modify the link somehow?

**Comment by felixroos** [comment]
This seems to work fine:

```js
import iRealReader from 'ireal-reader';
import { RealParser } from 'jazzband';

const playlist = iRealReader(decodeURI('irealb://Ali%C3%A1s%3DDjavan%3D%3DBallad%3DC%3D%3D1r34LbKcu7%2C6-bB4C%5E7XDZL7A%207bB%7CQyX7E-ZL9b7B%207h%23F%7CQy-%5E7%20s4TA*%5B7F%2096D-7%20G%20QyXQyX%5D%207G%207-ZDL7obE%207-E1NZL9LZN2Cl%7C%2C7ALZC%5E7XyQZ%20%3DLatin-Brazil:%20Bossa%20Acoustic%3D70%3D3%3D%3D%3D'))

jazzbandRealParser.parseSheet(playlist.songs[0].music.raw)
/*
[
  { chords: [ 'C^7' ], section: 'A', time: '44' },
  { chords: [ 'F#h7', 'B7b9' ] },
  { chords: [ 'E-7' ] },
  { chords: [ 'Bb7', 'A7' ] },
  { chords: [ 'D-^7', 'Bb-6', 'A7' ], signs: [ 's' ] },
  { chords: [ 'D-7', 'G9' ], signs: [ 'l' ] },
  { chords: [ 'E-7', 'Ebo7' ], house: 1 },
  { chords: [ 'D-7', 'G7' ] },
  { chords: [ 'C69', 'F7' ], house: 2 },
  { chords: [ 'C^7' ] }
]
*/
```

You can find most answers in the demo:

https://github.com/felixroos/jazzband/blob/master/demo/demo.js#L26
https://github.com/felixroos/jazzband/blob/master/demo/demo.js#L99

Please check out the demo first if something does'nt work, I'm happy to help, but this no support channel..
And if you're stuck, it always helps to post at least an error message, "doesn't work" is not helpful.

You can read more about ireal parsing in [this post](https://felixroos.github.io/blog/ireal-changes/)

**Comment by felixroos** [comment]
I stopped working on this lib, as I moved to developing [strudel](https://github.com/tidalcycles/strudel), which is similar (but much more powerful)
