### ISSUE TITLE
Idea: Major/Minor in chord groups

### ISSUE THREAD

**Issue by lastant** [felixroos/jazzband#8]
This is probably an idea for the upcoming harmonical package. Along "Basic", "Symmetric", "Triads", etc groups of chords it would be great to also have "Major" and "Minor", as this is an important property of the chords. Of course many chords cannot be classified this way, but most common ones can.

**Comment by felixroos** [comment]
I stopped working on this lib, as I moved to developing [strudel](https://github.com/tidalcycles/strudel), which is similar (but much more powerful)
