### ISSUE TITLE
RealParser.getSheet() issues

### ISSUE THREAD

**Issue by lastant** [felixroos/jazzband#9]
- `add9` and `7susadd3` are not parsed
- single repeat end brackets ( `}` instead of `}|` ) are not processed correctly: chords from the next measure are added to the current measure. Test: the 9th measure in `irealb://Saving%20All%20My%20Love%20For%20You%202%3DHouston%20Whitney%3D%3DMedium%20Swing%3DA%3D7%3D1r34LbKcu7%7C%7D%209d44A%5E7-BZL7-%23F%207%5EAZLd9daE%209-BZL7-%23F%209%20EadTA*%7BY-bA%207B%2FF%23L%2CE%2C7-%23Fs%2CbA%2F-%23%2CCAsZL%23F%2FB%207-%23FZ%7ClAb-%207-%23FbAB*%5BLZsD%5EXQyX%5DQyX7%5EAl%7D%2C%2FE7-B%2C7-B%2C7-%23C%2C7yQ%20%20Y%23C%2F7%5E7%5E%23CZ%237b9LA%2011-bE%7CQyX7%5EALZE%207-B%7CQyX7-%23FZb7b9LC%2011-XyQ%7CF%23-7%20B7LZEsus%20E%20%5D%20%3DJazz-Medium%20Swing%3D100%3D0%3D%3D%3D`

**Comment by felixroos** [comment]
I stopped working on this lib, as I moved to developing [strudel](https://github.com/tidalcycles/strudel), which is similar (but much more powerful)
